### ISSUE TITLE
Appreciation 

### ISSUE THREAD

**Issue by Helocominc** [bhagat-techind/flutter_sharing_intent#1]
Thank you @Bhagat9069 for this package. It's really a pain sharing stuff from other apps to flutter apps. Similar popular package is no longer maintained and outdated. 

I am glad for this package. Do keep it updated. I'm hoping other dev will start using this too. Thanks alot.

Do well to improve the documentation and how it works, to give a clearer detail of the package.

**Comment by bhagat-techind** [comment]
@Helocominc Thanks for appreciation.
Now plugin version `flutter_sharing_intent: ^1.0.2` is ready for use for both **Android** & **iOS**.
