### ISSUE TITLE
The detail infomation of `CUSTOM_GROUP_ID` is missed

### ISSUE THREAD

**Issue by HaloWang** [bhagat-techind/flutter_sharing_intent#10]
If I use `${CUSTOM_GROUP_ID}`, I will get an empty string (`""`) rather than `group.com.xxx.xxx` in runtime

```swift
let appGroupId = (Bundle.main.object(forInfoDictionaryKey: "AppGroupId") as? String) ?? "group.\(Bundle.main.bundleIdentifier!)"

let whatIsIt = Bundle.main.object(forInfoDictionaryKey: "AppGroupId") as? String
// `whatIsIt` is ""
// so `appGroupId` is "", in runtime
```

I need to change the value of AppGroupId to my group id explicitly, something like this:

```xml
<key>AppGroupId</key>
<string>group.com.XXXXX.XXXX</string>
```

**Comment by HaloWang** [comment]
This is the version info:

Xcode: Version 14.1 (14B47b)
iPhone: iPhone 13
iOS: 16.3.1

**Comment by bhagat-techind** [comment]
@HaloWang I have updated the doc.
