### ISSUE TITLE
Setup information for MacOS?

### ISSUE THREAD

**Issue by gisborne** [bhagat-techind/flutter_sharing_intent#13]
We claim support for MacOS, but there are no instructions.

I assume it's not *identical* to iOS…

**Comment by bhagat-techind** [comment]
@gisborne This plugin does not support MAC.

**Comment by mukhtharcm** [comment]
@gisborne Did you find any solution for macos?

**Comment by gisborne** [comment]
Currently focused on iOS using share_handler (successfully, so far).
