### ISSUE TITLE
Failed to build for Windows desktop

### ISSUE THREAD

**Issue by kenmasumitsu** [bhagat-techind/flutter_sharing_intent#27]
pubspec.yaml has `flutter.plugin.platforms.windows` key.  So that, it seems to support Windows desktop.

```pubspec.yaml
      windows:
        pluginClass: FlutterSharingIntentPluginCApi
```

However, as there is no windows folder, it does not support Windows desktop actually.   It caused building failure on Windows.

Could you remove `flutter.plugin.platforms.windows` in pubspec.yaml?

**Comment by bhagat-techind** [comment]
@kenmasumitsu I have updated the docs.
