### ISSUE TITLE
Null value on iOS

### ISSUE THREAD

**Issue by Advait1306** [bhagat-techind/flutter_sharing_intent#29]
I have tried using this plugin although I was successful in getting it to trigger when I send something to the app the values are always null.

<img width="529" alt="Screenshot 2023-09-04 at 11 38 45 PM" src="https://github.com/bhagat-techind/flutter_sharing_intent/assets/42912342/3065c8b0-4a0c-41ed-a79a-b9f98960765b">

I'm only trying to enable text and URL sharing.

I tried running the example project given by you - even that's returning null.

<img width="682" alt="Screenshot 2023-09-04 at 11 50 16 PM" src="https://github.com/bhagat-techind/flutter_sharing_intent/assets/42912342/dcc8954d-8a10-44d0-bf0e-d66e18d9e3e2">

The only thing I have changed is the order of build phases - because it wouldn't build without that. 

<img width="391" alt="Screenshot 2023-09-04 at 11 53 41 PM" src="https://github.com/bhagat-techind/flutter_sharing_intent/assets/42912342/24264240-7a98-460d-8349-03950514ca2f">

**Comment by pgyusz** [comment]
Same issue here

**Comment by tenraneko** [comment]
same

**Comment by Advait1306** [comment]
You can use this package, works pretty well & somehow has an awful lot of similarities in their code. [receive_sharing_intent](https://pub.dev/packages/receive_sharing_intent)

**Comment by pgyusz** [comment]
> You can use this package, works pretty well & somehow has an awful lot of similarities in their code. [receive_sharing_intent](https://pub.dev/packages/receive_sharing_intent)

Just tried it but it didn't work for me.

**Comment by pgyusz** [comment]
After debugging it in Xcode I found out that the ShareViewController.swift is not even executed. When I select the Share Extension as target and run it, then the ShareViewController.swift is executed, but when the selected target is the Runner, then it doesn't execute.

**Comment by FelixGaebler** [comment]
I have made the same observation as @pgyusz. Is there a workaround available?

**Comment by FelixGaebler** [comment]
I debugged some code yesterday and got the `ShareViewController` loading and running by replacing the `NSExtensionMainStoryboard` property in the `Info.plist` with `NSExtensionPrincipalClass` and prefix the value as required by xcode. The value (url/text) can both be printed. Anything fails between adding the values to the UserProperties and reading it on the flutter main app side. I will do further investigations later.

**Comment by vinothvino42** [comment]
> After debugging it in Xcode I found out that the ShareViewController.swift is not even executed. When I select the Share Extension as target and run it, then the ShareViewController.swift is executed, but when the selected target is the Runner, then it doesn't execute.

It's because the Share target will not run automatically when you run the main target. You need to attach a process (Share Extension) for debugging. In Xcode -> Debug -> Attach to process -> Enter your share extension name here. Then run your main target and now you can able to debug your share extension files in Xcode.

**Comment by pgyusz** [comment]
Thanks @vinothvino42, I can debug it but the problem is still not fixed.

**Comment by FelixGaebler** [comment]
I tested the implementation with some platform specific code (https://docs.flutter.dev/platform-integration/platform-channels) and it did work.
My next step is to debug the liberies code.

i had some extra steps to solve since I dont own a Mac.

**Comment by FelixGaebler** [comment]
@vinothvino42 do you have a hint on how to debug the libery sources?

**Comment by FelixGaebler** [comment]
```swift
print("urlFragment")
print(userDefaults)
print(userDefaults!.object(forKey: "SharingKey")!.self)
print(userDefaults?.object(forKey: "SharingKey") as? [String])
print(type(of: userDefaults!.object(forKey: "SharingKey")!))
```

```
urlFragment
Optional(<NSUserDefaults: 0x600000878090>)
{length = 260, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 000000ca }
nil
__NSCFData
```

**Comment by FelixGaebler** [comment]
I strongly recommend to review and merge the open pull request https://github.com/bhagat-techind/flutter_sharing_intent/pull/21 since it brings some improvements.
Anyways: the fix is not included, but I found it.

https://github.com/bhagat-techind/flutter_sharing_intent/blob/main/lib/model/sharing_file.dart#L24
as to be changed to:
`json['value'] ?? json['path']`

**Comment by FelixGaebler** [comment]
I opened a PR with my fix https://github.com/bhagat-techind/flutter_sharing_intent/pull/34

**Comment by FelixGaebler** [comment]
Temporary fix:
1. go to pubspec.yaml
2. change 
```yaml
flutter_sharing_intent: ^1.1.0
```
to
```yaml
flutter_sharing_intent:
  git: https://github.com/FelixGaebler/flutter_sharing_intent.git
```

**Comment by pgyusz** [comment]
@FelixGaebler It now works with sharing links, but with photos not
<img width="532" alt="Screenshot 2023-10-04 at 09 39 54" src="https://github.com/bhagat-techind/flutter_sharing_intent/assets/126097135/016e209a-10c4-43a0-bb41-f1a5975785ae">

**Comment by tmratwork** [comment]
I changed pubspec.yaml to:
```
  flutter_sharing_intent:
    git:
      url: https://github.com/FelixGaebler/flutter_sharing_intent.git

```

but still getting a null error:
`[User Defaults] Couldn't read values in CFPrefsPlistSource<0x282688c00> (Domain: group.Q9D95M66R6.com.vorail.tubetalkers, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd`

is this the error others are getting in iOS? everything working great in android. I am testing on a iPhone X. i run the  flutter_sharing_intent example app, then open YouTube, select share on a YouTube video. the flutter_sharing_intent example app auto comes to foreground, but nothing shows on the screen and debug window shows message above about Container: (null).

any suggestions?

**Comment by regissafari** [comment]
> @FelixGaebler It now works with sharing links, but with photos not <img alt="Screenshot 2023-10-04 at 09 39 54" width="532" src="https://user-images.githubusercontent.com/126097135/272484207-016e209a-10c4-43a0-bb41-f1a5975785ae.png">

Bro, am getting the same issue as well:

> flutter_sharing_intent/SwiftFlutterSharingIntentPlugin.swift:253: Fatal error: The data couldn’t be read because it is missing.
Lost connection to device.
Exception: Unable to terminate com.my.app on 5B3FB406-29EC-4A69-8846-2ACC8430370F:
ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=3):
Simulator device returned an error for the requested operation.
found nothing to terminate
Underlying error (domain=NSPOSIXErrorDomain, code=3):
	The request to terminate "com.my.app" failed. found nothing to terminate
	found nothing to terminate
  Command: /usr/bin/arch -arm64e xcrun simctl terminate 5B3FB406-29EC-4A69-8846-2ACC8430370F com.my.app

**Comment by Firooz-Smart** [comment]
i solved the problem by cloning the pull request #21 
 the problem with receiving text/url and image is solved here.
 Thanks

**Comment by Firooz-Smart** [comment]
> I strongly recommend to review and merge the open pull request #21 since it brings some improvements. Anyways: the fix is not included, but I found it.
> 
> https://github.com/bhagat-techind/flutter_sharing_intent/blob/main/lib/model/sharing_file.dart#L24 as to be changed to: `json['value'] ?? json['path']`

Worked for me

**Comment by sagarSaw** [comment]
**<img width="825" alt="Screenshot 2024-01-11 at 6 12 17 PM" src="https://github.com/bhagat-techind/flutter_sharing_intent/assets/23626954/35966545-8974-4577-b8af-8b3512c73cb3">**
The issue is with decoding the file data in **SharingFile** the value is decoding with path key which is wrong. 
We just need to remove the path key and make the value var optional. Now It worked for me.

Thanks.
