### ISSUE TITLE
Caching issue / outdated intent

### ISSUE THREAD

**Issue by razfazz** [bhagat-techind/flutter_sharing_intent#5]
I am using this package in my application and in some cases. mostly when the app was not used for some time and I share a link with this app, the link which is then received is an old link which was shared before.

**Comment by zogol** [comment]
i have the same issue. hopefully this gets fixed soon

**Comment by bhagat-techind** [comment]
Call reset method on successfully get data.
`FlutterSharingIntent.instance.reset();`
I will fix this soon.

**Comment by bhagat-techind** [comment]
@zogol @razfazz I have fixed this issue. Please use new version 1.0.6 for this library.
If this is done, Please close this issue.
